import requests                                                                                                                                                                                                                        
import os                                                                                                                                                                                                                              
                                                                                                                                                                                                                                       
host=os.environ['KUBERNETES_SERVICE_HOST']                                                                                                                                                                                             
                                                                                                                                                                                                                                       
tokenfile = open('/var/run/secrets/kubernetes.io/serviceaccount/token','r')                                                                                                                                                            
                                                                                                                                                                                                                                       
token=file.read()                                                                                                                                                                                                                      
                                                                                                                                                                                                                                       
url = 'https://' + host + ':8443/oapi/v1'                                                                                                                                                                                              
                                                                                                                                                                                                                                       
headers = {'Authorization': 'Bearer ' + token}                                                                                                                                                                                         
requests.get(url, headers=headers, verify=False)  
